package com.myteam.tts_connected_claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class customerDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("id")
	private String id;

	@org.kie.api.definition.type.Label("contactType")
	private java.lang.String contactType;

	@org.kie.api.definition.type.Label("email")
	private java.lang.String email;

	@javax.persistence.ManyToOne(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	@org.kie.api.definition.type.Label("address")
	private com.myteam.tts_connected_claims.address address;

	@org.kie.api.definition.type.Label("customerFirstName")
	private java.lang.String customerFirstName;

	@org.kie.api.definition.type.Label("customerSurname")
	private java.lang.String customerSurName;

	@org.kie.api.definition.type.Label("customerInitials")
	private java.lang.String customerInitials;

	@org.kie.api.definition.type.Label("dateOfBirth")
	private String dateOfBirth;

	@org.kie.api.definition.type.Label(value = "contactNumber")
	private java.lang.String contactNumber;

	public customerDetails() {
	}

	public java.lang.String getContactType() {
		return this.contactType;
	}

	public void setContactType(java.lang.String contactType) {
		this.contactType = contactType;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public com.myteam.tts_connected_claims.address getAddress() {
		return this.address;
	}

	public void setAddress(com.myteam.tts_connected_claims.address address) {
		this.address = address;
	}

	public java.lang.String getCustomerFirstName() {
		return this.customerFirstName;
	}

	public void setCustomerFirstName(java.lang.String customerFirstName) {
		this.customerFirstName = customerFirstName;
	}

	public java.lang.String getCustomerSurName() {
		return this.customerSurName;
	}

	public void setCustomerSurName(java.lang.String customerSurName) {
		this.customerSurName = customerSurName;
	}

	public java.lang.String getCustomerInitials() {
		return this.customerInitials;
	}

	public void setCustomerInitials(java.lang.String customerInitials) {
		this.customerInitials = customerInitials;
	}

	public java.lang.String getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(java.lang.String dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public java.lang.String getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(java.lang.String contactNumber) {
		this.contactNumber = contactNumber;
	}

	public customerDetails(java.lang.String id, java.lang.String contactType,
			java.lang.String email,
			com.myteam.tts_connected_claims.address address,
			java.lang.String customerFirstName,
			java.lang.String customerSurName,
			java.lang.String customerInitials, java.lang.String dateOfBirth,
			java.lang.String contactNumber) {
		this.id = id;
		this.contactType = contactType;
		this.email = email;
		this.address = address;
		this.customerFirstName = customerFirstName;
		this.customerSurName = customerSurName;
		this.customerInitials = customerInitials;
		this.dateOfBirth = dateOfBirth;
		this.contactNumber = contactNumber;
	}

}