package com.myteam.tts_connected_claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class members implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "customerFirstName")
	private java.lang.String customerFirstName;

	@org.kie.api.definition.type.Label(value = "customerInitials")
	private java.lang.String customerInitials;

	@org.kie.api.definition.type.Label(value = "customerSurname")
	private java.lang.String customerSurname;

	@org.kie.api.definition.type.Label(value = "role")
	private java.lang.String role;

	@org.kie.api.definition.type.Label(value = "contactNumber")
	private java.lang.String contactNumber;

	public members() {
	}

	public java.lang.String getCustomerFirstName() {
		return this.customerFirstName;
	}

	public void setCustomerFirstName(java.lang.String customerFirstName) {
		this.customerFirstName = customerFirstName;
	}

	public java.lang.String getCustomerInitials() {
		return this.customerInitials;
	}

	public void setCustomerInitials(java.lang.String customerInitials) {
		this.customerInitials = customerInitials;
	}

	public java.lang.String getCustomerSurname() {
		return this.customerSurname;
	}

	public void setCustomerSurname(java.lang.String customerSurname) {
		this.customerSurname = customerSurname;
	}

	public java.lang.String getRole() {
		return this.role;
	}

	public void setRole(java.lang.String role) {
		this.role = role;
	}

	public java.lang.String getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(java.lang.String contactNumber) {
		this.contactNumber = contactNumber;
	}

	public members(java.lang.String customerFirstName,
			java.lang.String customerInitials,
			java.lang.String customerSurname, java.lang.String role,
			java.lang.String contactNumber) {
		this.customerFirstName = customerFirstName;
		this.customerInitials = customerInitials;
		this.customerSurname = customerSurname;
		this.role = role;
		this.contactNumber = contactNumber;
	}

}