package com.myteam.tts_connected_claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class policyDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("policyNumber")
	private java.lang.String policyNumber;

	@org.kie.api.definition.type.Label("policyBrand")
	private java.lang.String policyBrand;

	@org.kie.api.definition.type.Label("policyStatus")
	private java.lang.String policyStatus;

	@org.kie.api.definition.type.Label("policyHolderFirstName")
	private java.lang.String policyHolderFirstName;

	@org.kie.api.definition.type.Label("policyHolderSurname")
	private java.lang.String policyHolderSurname;

	@org.kie.api.definition.type.Label("policyHolderInitials")
	private java.lang.String policyHolderInitials;

	@javax.persistence.OneToMany(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	@org.kie.api.definition.type.Label(value = "members")
	private java.util.List<com.myteam.tts_connected_claims.members> members;

	@javax.persistence.OneToMany(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	@org.kie.api.definition.type.Label(value = "vehicles")
	private java.util.List<com.myteam.tts_connected_claims.vehicles> vehicles;

	public policyDetails() {
	}

	public java.lang.String getPolicyNumber() {
		return this.policyNumber;
	}

	public void setPolicyNumber(java.lang.String policyNumber) {
		this.policyNumber = policyNumber;
	}

	public java.lang.String getPolicyBrand() {
		return this.policyBrand;
	}

	public void setPolicyBrand(java.lang.String policyBrand) {
		this.policyBrand = policyBrand;
	}

	public java.lang.String getPolicyStatus() {
		return this.policyStatus;
	}

	public void setPolicyStatus(java.lang.String policyStatus) {
		this.policyStatus = policyStatus;
	}

	public java.lang.String getPolicyHolderFirstName() {
		return this.policyHolderFirstName;
	}

	public void setPolicyHolderFirstName(java.lang.String policyHolderFirstName) {
		this.policyHolderFirstName = policyHolderFirstName;
	}

	public java.lang.String getPolicyHolderSurname() {
		return this.policyHolderSurname;
	}

	public void setPolicyHolderSurname(java.lang.String policyHolderSurname) {
		this.policyHolderSurname = policyHolderSurname;
	}

	public java.lang.String getPolicyHolderInitials() {
		return this.policyHolderInitials;
	}

	public void setPolicyHolderInitials(java.lang.String policyHolderInitials) {
		this.policyHolderInitials = policyHolderInitials;
	}

	public java.util.List<com.myteam.tts_connected_claims.members> getMembers() {
		return this.members;
	}

	public void setMembers(
			java.util.List<com.myteam.tts_connected_claims.members> members) {
		this.members = members;
	}

	public java.util.List<com.myteam.tts_connected_claims.vehicles> getVehicles() {
		return this.vehicles;
	}

	public void setVehicles(
			java.util.List<com.myteam.tts_connected_claims.vehicles> vehicles) {
		this.vehicles = vehicles;
	}

	public policyDetails(java.lang.String policyNumber,
			java.lang.String policyBrand, java.lang.String policyStatus,
			java.lang.String policyHolderFirstName,
			java.lang.String policyHolderSurname,
			java.lang.String policyHolderInitials,
			java.util.List<com.myteam.tts_connected_claims.members> members,
			java.util.List<com.myteam.tts_connected_claims.vehicles> vehicles) {
		this.policyNumber = policyNumber;
		this.policyBrand = policyBrand;
		this.policyStatus = policyStatus;
		this.policyHolderFirstName = policyHolderFirstName;
		this.policyHolderSurname = policyHolderSurname;
		this.policyHolderInitials = policyHolderInitials;
		this.members = members;
		this.vehicles = vehicles;
	}

}