package com.myteam.tts_connected_claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class serviceOffering implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("serviceName")
	private java.lang.String serviceName;

	@org.kie.api.definition.type.Label("serviceStatus")
	private java.lang.String serviceStatus;

	@org.kie.api.definition.type.Label("requestTime")
	private String requestTime;

	@org.kie.api.definition.type.Label("serviceType")
	private java.lang.String serviceType;

	@org.kie.api.definition.type.Label(value = "serviceId")
	private java.lang.String serviceId;

	@org.kie.api.definition.type.Label(value = "progress")
	private java.lang.String progress;

	@org.kie.api.definition.type.Label(value = "color")
	private java.lang.String color;

	public serviceOffering() {
	}

	public java.lang.String getServiceName() {
		return this.serviceName;
	}

	public void setServiceName(java.lang.String serviceName) {
		this.serviceName = serviceName;
	}

	public java.lang.String getServiceStatus() {
		return this.serviceStatus;
	}

	public void setServiceStatus(java.lang.String serviceStatus) {
		this.serviceStatus = serviceStatus;
	}

	public java.lang.String getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(java.lang.String serviceType) {
		this.serviceType = serviceType;
	}

	public java.lang.String getRequestTime() {
		return this.requestTime;
	}

	public void setRequestTime(java.lang.String requestTime) {
		this.requestTime = requestTime;
	}

	public java.lang.String getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(java.lang.String serviceId) {
		this.serviceId = serviceId;
	}

	public java.lang.String getProgress() {
		return this.progress;
	}

	public void setProgress(java.lang.String progress) {
		this.progress = progress;
	}

	public java.lang.String getColor() {
		return this.color;
	}

	public void setColor(java.lang.String color) {
		this.color = color;
	}

	public serviceOffering(java.lang.String serviceName,
			java.lang.String serviceStatus, java.lang.String requestTime,
			java.lang.String serviceType, java.lang.String serviceId,
			java.lang.String progress, java.lang.String color) {
		this.serviceName = serviceName;
		this.serviceStatus = serviceStatus;
		this.requestTime = requestTime;
		this.serviceType = serviceType;
		this.serviceId = serviceId;
		this.progress = progress;
		this.color = color;
	}

}