package com.myteam.tts_connected_claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class policyDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("policyNumber")
	private java.lang.String policyNumber;

	@org.kie.api.definition.type.Label("policyBrand")
	private java.lang.String policyBrand;

	@org.kie.api.definition.type.Label("policyStatus")
	private java.lang.String policyStatus;

	@org.kie.api.definition.type.Label("policyHolderFirstName")
	private java.lang.String policyHolderFirstName;

	@org.kie.api.definition.type.Label("policyHolderSurname")
	private java.lang.String policyHolderSurname;

	@org.kie.api.definition.type.Label("policyHolderInitials")
	private java.lang.String policyHolderInitials;

	@javax.persistence.OneToMany(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	@org.kie.api.definition.type.Label("members")
	private java.util.List<com.myteam.tts_connected_claims.members> members;

	@javax.persistence.OneToMany(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	@org.kie.api.definition.type.Label("vehicles")
	private java.util.List<com.myteam.tts_connected_claims.vehicles> vehicles;

	@org.kie.api.definition.type.Label(value = "id")
	private java.lang.String id;

	@org.kie.api.definition.type.Label(value = "email")
	private java.lang.String email;

	@org.kie.api.definition.type.Label(value = "contactNumber")
	private java.lang.String contactNumber;

	@org.kie.api.definition.type.Label(value = "dateOfBirth")
	private java.lang.String dateOfBirth;

	public policyDetails() {
	}

	public java.lang.String getPolicyNumber() {
		return this.policyNumber;
	}

	public void setPolicyNumber(java.lang.String policyNumber) {
		this.policyNumber = policyNumber;
	}

	public java.lang.String getPolicyBrand() {
		return this.policyBrand;
	}

	public void setPolicyBrand(java.lang.String policyBrand) {
		this.policyBrand = policyBrand;
	}

	public java.lang.String getPolicyStatus() {
		return this.policyStatus;
	}

	public void setPolicyStatus(java.lang.String policyStatus) {
		this.policyStatus = policyStatus;
	}

	public java.lang.String getPolicyHolderFirstName() {
		return this.policyHolderFirstName;
	}

	public void setPolicyHolderFirstName(java.lang.String policyHolderFirstName) {
		this.policyHolderFirstName = policyHolderFirstName;
	}

	public java.lang.String getPolicyHolderSurname() {
		return this.policyHolderSurname;
	}

	public void setPolicyHolderSurname(java.lang.String policyHolderSurname) {
		this.policyHolderSurname = policyHolderSurname;
	}

	public java.lang.String getPolicyHolderInitials() {
		return this.policyHolderInitials;
	}

	public void setPolicyHolderInitials(java.lang.String policyHolderInitials) {
		this.policyHolderInitials = policyHolderInitials;
	}

	public java.util.List<com.myteam.tts_connected_claims.members> getMembers() {
		return this.members;
	}

	public void setMembers(
			java.util.List<com.myteam.tts_connected_claims.members> members) {
		this.members = members;
	}

	public java.util.List<com.myteam.tts_connected_claims.vehicles> getVehicles() {
		return this.vehicles;
	}

	public void setVehicles(
			java.util.List<com.myteam.tts_connected_claims.vehicles> vehicles) {
		this.vehicles = vehicles;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(java.lang.String contactNumber) {
		this.contactNumber = contactNumber;
	}

	public java.lang.String getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(java.lang.String dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public policyDetails(java.lang.String policyNumber,
			java.lang.String policyBrand, java.lang.String policyStatus,
			java.lang.String policyHolderFirstName,
			java.lang.String policyHolderSurname,
			java.lang.String policyHolderInitials,
			java.util.List<com.myteam.tts_connected_claims.members> members,
			java.util.List<com.myteam.tts_connected_claims.vehicles> vehicles,
			java.lang.String id, java.lang.String email,
			java.lang.String contactNumber, java.lang.String dateOfBirth) {
		this.policyNumber = policyNumber;
		this.policyBrand = policyBrand;
		this.policyStatus = policyStatus;
		this.policyHolderFirstName = policyHolderFirstName;
		this.policyHolderSurname = policyHolderSurname;
		this.policyHolderInitials = policyHolderInitials;
		this.members = members;
		this.vehicles = vehicles;
		this.id = id;
		this.email = email;
		this.contactNumber = contactNumber;
		this.dateOfBirth = dateOfBirth;
	}

}