package com.myteam.tts_connected_claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class representative implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "contactNumber")
	private java.lang.String contactNumber;
	@org.kie.api.definition.type.Label(value = "email")
	private java.lang.String email;
	@org.kie.api.definition.type.Label(value = "firstName")
	private java.lang.String firstName;
	@org.kie.api.definition.type.Label(value = "surname")
	private java.lang.String surname;

	public representative() {
	}

	public java.lang.String getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(java.lang.String contactNumber) {
		this.contactNumber = contactNumber;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(java.lang.String firstName) {
		this.firstName = firstName;
	}

	public java.lang.String getSurname() {
		return this.surname;
	}

	public void setSurname(java.lang.String surname) {
		this.surname = surname;
	}

	public representative(java.lang.String contactNumber,
			java.lang.String email, java.lang.String firstName,
			java.lang.String surname) {
		this.contactNumber = contactNumber;
		this.email = email;
		this.firstName = firstName;
		this.surname = surname;
	}

}