package com.myteam.tts_connected_claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class serviceOffering implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("serviceName")
	private java.lang.String serviceName;

	@org.kie.api.definition.type.Label("serviceStatus")
	private java.lang.String serviceStatus;

	@org.kie.api.definition.type.Label("progress")
	private java.lang.String progress;

	@org.kie.api.definition.type.Label("color")
	private java.lang.String color;

	@org.kie.api.definition.type.Label("serviceType")
	private java.lang.String serviceType;

	@org.kie.api.definition.type.Label(value = "eligible")
	private java.lang.Boolean eligible;

	public serviceOffering() {
	}

	public java.lang.String getServiceName() {
		return this.serviceName;
	}

	public void setServiceName(java.lang.String serviceName) {
		this.serviceName = serviceName;
	}

	public java.lang.String getServiceStatus() {
		return this.serviceStatus;
	}

	public void setServiceStatus(java.lang.String serviceStatus) {
		this.serviceStatus = serviceStatus;
	}

	public java.lang.String getProgress() {
		return this.progress;
	}

	public void setProgress(java.lang.String progress) {
		this.progress = progress;
	}

	public java.lang.String getColor() {
		return this.color;
	}

	public void setColor(java.lang.String color) {
		this.color = color;
	}

	public java.lang.String getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(java.lang.String serviceType) {
		this.serviceType = serviceType;
	}

	public java.lang.Boolean getEligible() {
		return this.eligible;
	}

	public void setEligible(java.lang.Boolean eligible) {
		this.eligible = eligible;
	}

	public serviceOffering(java.lang.String serviceName,
			java.lang.String serviceStatus, java.lang.String progress,
			java.lang.String color, java.lang.String serviceType,
			java.lang.Boolean eligible) {
		this.serviceName = serviceName;
		this.serviceStatus = serviceStatus;
		this.progress = progress;
		this.color = color;
		this.serviceType = serviceType;
		this.eligible = eligible;
	}

}