package com.myteam.tts_connected_claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class services implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "ambulance")
	private java.lang.Boolean ambulance;

	@org.kie.api.definition.type.Label(value = "towing")
	private java.lang.Boolean towing;

	@org.kie.api.definition.type.Label(value = "roadsideAssist")
	private java.lang.Boolean roadsideAssist;

	@org.kie.api.definition.type.Label(value = "taxi")
	private java.lang.Boolean taxi;

	@org.kie.api.definition.type.Label(value = "carHire")
	private java.lang.Boolean carHire;

	public services() {
	}

	public java.lang.Boolean getAmbulance() {
		return this.ambulance;
	}

	public void setAmbulance(java.lang.Boolean ambulance) {
		this.ambulance = ambulance;
	}

	public java.lang.Boolean getTowing() {
		return this.towing;
	}

	public void setTowing(java.lang.Boolean towing) {
		this.towing = towing;
	}

	public java.lang.Boolean getRoadsideAssist() {
		return this.roadsideAssist;
	}

	public void setRoadsideAssist(java.lang.Boolean roadsideAssist) {
		this.roadsideAssist = roadsideAssist;
	}

	public java.lang.Boolean getTaxi() {
		return this.taxi;
	}

	public void setTaxi(java.lang.Boolean taxi) {
		this.taxi = taxi;
	}

	public java.lang.Boolean getCarHire() {
		return this.carHire;
	}

	public void setCarHire(java.lang.Boolean carHire) {
		this.carHire = carHire;
	}

	public services(java.lang.Boolean ambulance, java.lang.Boolean towing,
			java.lang.Boolean roadsideAssist, java.lang.Boolean taxi,
			java.lang.Boolean carHire) {
		this.ambulance = ambulance;
		this.towing = towing;
		this.roadsideAssist = roadsideAssist;
		this.taxi = taxi;
		this.carHire = carHire;
	}

}