package com.myteam.tts_connected_claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class serviceOffering implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "serviceName")
	private java.lang.String serviceName;

	@org.kie.api.definition.type.Label(value = "serviceStatus")
	private java.lang.String serviceStatus;

	@org.kie.api.definition.type.Label(value = "requestTime")
	private java.util.Date requestTime;

	@org.kie.api.definition.type.Label(value = "serviceType")
	private java.lang.String serviceType;

	public serviceOffering() {
	}

	public java.lang.String getServiceName() {
		return this.serviceName;
	}

	public void setServiceName(java.lang.String serviceName) {
		this.serviceName = serviceName;
	}

	public java.lang.String getServiceStatus() {
		return this.serviceStatus;
	}

	public void setServiceStatus(java.lang.String serviceStatus) {
		this.serviceStatus = serviceStatus;
	}

	public java.util.Date getRequestTime() {
		return this.requestTime;
	}

	public void setRequestTime(java.util.Date requestTime) {
		this.requestTime = requestTime;
	}

	public java.lang.String getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(java.lang.String serviceType) {
		this.serviceType = serviceType;
	}

	public serviceOffering(java.lang.String serviceName,
			java.lang.String serviceStatus, java.util.Date requestTime,
			java.lang.String serviceType) {
		this.serviceName = serviceName;
		this.serviceStatus = serviceStatus;
		this.requestTime = requestTime;
		this.serviceType = serviceType;
	}

}