package com.myteam.tts_connected_claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class serviceProviderAssignment implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "authorizationReference")
	private java.lang.String authorizationReference;
	@org.kie.api.definition.type.Label(value = "dateAssigned")
	private java.lang.String dateAssigned;
	@org.kie.api.definition.type.Label(value = "dispatchLocation")
	private com.myteam.tts_connected_claims.location dispatchLocation;
	@org.kie.api.definition.type.Label(value = "kilometersToIncidentByRoad")
	private java.lang.String kilometersToIncidentByRoad;
	@org.kie.api.definition.type.Label(value = "representative")
	private com.myteam.tts_connected_claims.representative representative;
	@org.kie.api.definition.type.Label(value = "representativePhotoUrl")
	private java.lang.String representativePhotoUrl;

	public serviceProviderAssignment() {
	}

	public java.lang.String getAuthorizationReference() {
		return this.authorizationReference;
	}

	public void setAuthorizationReference(
			java.lang.String authorizationReference) {
		this.authorizationReference = authorizationReference;
	}

	public java.lang.String getDateAssigned() {
		return this.dateAssigned;
	}

	public void setDateAssigned(java.lang.String dateAssigned) {
		this.dateAssigned = dateAssigned;
	}

	public com.myteam.tts_connected_claims.location getDispatchLocation() {
		return this.dispatchLocation;
	}

	public void setDispatchLocation(
			com.myteam.tts_connected_claims.location dispatchLocation) {
		this.dispatchLocation = dispatchLocation;
	}

	public java.lang.String getKilometersToIncidentByRoad() {
		return this.kilometersToIncidentByRoad;
	}

	public void setKilometersToIncidentByRoad(
			java.lang.String kilometersToIncidentByRoad) {
		this.kilometersToIncidentByRoad = kilometersToIncidentByRoad;
	}

	public com.myteam.tts_connected_claims.representative getRepresentative() {
		return this.representative;
	}

	public void setRepresentative(
			com.myteam.tts_connected_claims.representative representative) {
		this.representative = representative;
	}

	public java.lang.String getRepresentativePhotoUrl() {
		return this.representativePhotoUrl;
	}

	public void setRepresentativePhotoUrl(
			java.lang.String representativePhotoUrl) {
		this.representativePhotoUrl = representativePhotoUrl;
	}

	public serviceProviderAssignment(java.lang.String authorizationReference,
			java.lang.String dateAssigned,
			com.myteam.tts_connected_claims.location dispatchLocation,
			java.lang.String kilometersToIncidentByRoad,
			com.myteam.tts_connected_claims.representative representative,
			java.lang.String representativePhotoUrl) {
		this.authorizationReference = authorizationReference;
		this.dateAssigned = dateAssigned;
		this.dispatchLocation = dispatchLocation;
		this.kilometersToIncidentByRoad = kilometersToIncidentByRoad;
		this.representative = representative;
		this.representativePhotoUrl = representativePhotoUrl;
	}

}