package com.myteam.tts_connected_claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class serviceProviderCustomerLiasion implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "contactNumber")
	private java.lang.String contactNumber;
	@org.kie.api.definition.type.Label(value = "hierarchyDescription")
	private java.lang.String hierarchyDescription;
	@org.kie.api.definition.type.Label(value = "representative")
	private com.myteam.tts_connected_claims.representative representative;

	public serviceProviderCustomerLiasion() {
	}

	public java.lang.String getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(java.lang.String contactNumber) {
		this.contactNumber = contactNumber;
	}

	public java.lang.String getHierarchyDescription() {
		return this.hierarchyDescription;
	}

	public void setHierarchyDescription(java.lang.String hierarchyDescription) {
		this.hierarchyDescription = hierarchyDescription;
	}

	public com.myteam.tts_connected_claims.representative getRepresentative() {
		return this.representative;
	}

	public void setRepresentative(
			com.myteam.tts_connected_claims.representative representative) {
		this.representative = representative;
	}

	public serviceProviderCustomerLiasion(java.lang.String contactNumber,
			java.lang.String hierarchyDescription,
			com.myteam.tts_connected_claims.representative representative) {
		this.contactNumber = contactNumber;
		this.hierarchyDescription = hierarchyDescription;
		this.representative = representative;
	}

}