package com.myteam.tts_connected_claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class serviceDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("actualDestination")
	private com.myteam.tts_connected_claims.location actualDestination;
	@org.kie.api.definition.type.Label("containerId")
	private java.lang.String containerId;
	@org.kie.api.definition.type.Label("customerDirectedDestination")
	private com.myteam.tts_connected_claims.location customerDirectedDestination;
	@org.kie.api.definition.type.Label("directedDestination")
	private com.myteam.tts_connected_claims.location directedDestination;
	@org.kie.api.definition.type.Label("incidentCaseType")
	private java.lang.String incidentCaseType;
	@org.kie.api.definition.type.Label("incidentId")
	private java.lang.String incidentId;
	@org.kie.api.definition.type.Label("incidentLocation")
	private com.myteam.tts_connected_claims.location incidentLocation;
	@org.kie.api.definition.type.Label("incidentServiceType")
	private java.lang.String incidentServiceType;
	@org.kie.api.definition.type.Label("instructionsToServiceProvider")
	private java.lang.String instructionsToServiceProvider;
	@org.kie.api.definition.type.Label("parentId")
	private java.lang.String parentId;
	@org.kie.api.definition.type.Label("processId")
	private java.lang.String processId;
	@org.kie.api.definition.type.Label("requestor")
	private java.lang.String requestor;
	@org.kie.api.definition.type.Label("serviceId")
	private java.lang.String serviceId;
	@org.kie.api.definition.type.Label("serviceName")
	private java.lang.String serviceName;
	@org.kie.api.definition.type.Label("serviceProcessId")
	private java.lang.String serviceProcessId;
	@org.kie.api.definition.type.Label("serviceProvider")
	private com.myteam.tts_connected_claims.serviceProvider serviceProvider;
	@org.kie.api.definition.type.Label("serviceProviderCustomerLiaison")
	private com.myteam.tts_connected_claims.serviceProviderCustomerLiasion serviceProviderCustomerLiaison;
	@org.kie.api.definition.type.Label("serviceProviderLiaison")
	private com.myteam.tts_connected_claims.serviceProviderLiaison serviceProviderLiaison;
	@org.kie.api.definition.type.Label("serviceProviderOnscene")
	private java.lang.String serviceProviderOnscene;
	@org.kie.api.definition.type.Label("serviceStatus")
	private java.lang.String serviceStatus;
	@org.kie.api.definition.type.Label("serviceTimeline")
	private java.util.List<com.myteam.tts_connected_claims.serviceTimelines> serviceTimeline;
	@org.kie.api.definition.type.Label("serviceTriggerSource")
	private java.lang.String serviceTriggerSource;
	@org.kie.api.definition.type.Label("serviceType")
	private java.lang.String serviceType;
	@org.kie.api.definition.type.Label("vendorCaseCreatedTime")
	private java.lang.String vendorCaseCreatedTime;

	@org.kie.api.definition.type.Label(value = "vendorCaseId")
	private java.lang.String vendorCaseId;

	@org.kie.api.definition.type.Label(value = "vendorName")
	private java.lang.String vendorName;

	@org.kie.api.definition.type.Label(value = "vendorServiceCreatedTime")
	private java.lang.String vendorServiceCreatedTime;

	@org.kie.api.definition.type.Label(value = "vendorServiceId")
	private java.lang.String vendorServiceId;

	public serviceDetails() {
	}

	public com.myteam.tts_connected_claims.location getActualDestination() {
		return this.actualDestination;
	}

	public void setActualDestination(
			com.myteam.tts_connected_claims.location actualDestination) {
		this.actualDestination = actualDestination;
	}

	public java.lang.String getContainerId() {
		return this.containerId;
	}

	public void setContainerId(java.lang.String containerId) {
		this.containerId = containerId;
	}

	public com.myteam.tts_connected_claims.location getCustomerDirectedDestination() {
		return this.customerDirectedDestination;
	}

	public void setCustomerDirectedDestination(
			com.myteam.tts_connected_claims.location customerDirectedDestination) {
		this.customerDirectedDestination = customerDirectedDestination;
	}

	public com.myteam.tts_connected_claims.location getDirectedDestination() {
		return this.directedDestination;
	}

	public void setDirectedDestination(
			com.myteam.tts_connected_claims.location directedDestination) {
		this.directedDestination = directedDestination;
	}

	public java.lang.String getIncidentCaseType() {
		return this.incidentCaseType;
	}

	public void setIncidentCaseType(java.lang.String incidentCaseType) {
		this.incidentCaseType = incidentCaseType;
	}

	public java.lang.String getIncidentId() {
		return this.incidentId;
	}

	public void setIncidentId(java.lang.String incidentId) {
		this.incidentId = incidentId;
	}

	public com.myteam.tts_connected_claims.location getIncidentLocation() {
		return this.incidentLocation;
	}

	public void setIncidentLocation(
			com.myteam.tts_connected_claims.location incidentLocation) {
		this.incidentLocation = incidentLocation;
	}

	public java.lang.String getIncidentServiceType() {
		return this.incidentServiceType;
	}

	public void setIncidentServiceType(java.lang.String incidentServiceType) {
		this.incidentServiceType = incidentServiceType;
	}

	public java.lang.String getInstructionsToServiceProvider() {
		return this.instructionsToServiceProvider;
	}

	public void setInstructionsToServiceProvider(
			java.lang.String instructionsToServiceProvider) {
		this.instructionsToServiceProvider = instructionsToServiceProvider;
	}

	public java.lang.String getParentId() {
		return this.parentId;
	}

	public void setParentId(java.lang.String parentId) {
		this.parentId = parentId;
	}

	public java.lang.String getProcessId() {
		return this.processId;
	}

	public void setProcessId(java.lang.String processId) {
		this.processId = processId;
	}

	public java.lang.String getRequestor() {
		return this.requestor;
	}

	public void setRequestor(java.lang.String requestor) {
		this.requestor = requestor;
	}

	public java.lang.String getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(java.lang.String serviceId) {
		this.serviceId = serviceId;
	}

	public java.lang.String getServiceName() {
		return this.serviceName;
	}

	public void setServiceName(java.lang.String serviceName) {
		this.serviceName = serviceName;
	}

	public java.lang.String getServiceProcessId() {
		return this.serviceProcessId;
	}

	public void setServiceProcessId(java.lang.String serviceProcessId) {
		this.serviceProcessId = serviceProcessId;
	}

	public com.myteam.tts_connected_claims.serviceProvider getServiceProvider() {
		return this.serviceProvider;
	}

	public void setServiceProvider(
			com.myteam.tts_connected_claims.serviceProvider serviceProvider) {
		this.serviceProvider = serviceProvider;
	}

	public com.myteam.tts_connected_claims.serviceProviderCustomerLiasion getServiceProviderCustomerLiaison() {
		return this.serviceProviderCustomerLiaison;
	}

	public void setServiceProviderCustomerLiaison(
			com.myteam.tts_connected_claims.serviceProviderCustomerLiasion serviceProviderCustomerLiaison) {
		this.serviceProviderCustomerLiaison = serviceProviderCustomerLiaison;
	}

	public com.myteam.tts_connected_claims.serviceProviderLiaison getServiceProviderLiaison() {
		return this.serviceProviderLiaison;
	}

	public void setServiceProviderLiaison(
			com.myteam.tts_connected_claims.serviceProviderLiaison serviceProviderLiaison) {
		this.serviceProviderLiaison = serviceProviderLiaison;
	}

	public java.lang.String getServiceProviderOnscene() {
		return this.serviceProviderOnscene;
	}

	public void setServiceProviderOnscene(
			java.lang.String serviceProviderOnscene) {
		this.serviceProviderOnscene = serviceProviderOnscene;
	}

	public java.lang.String getServiceStatus() {
		return this.serviceStatus;
	}

	public void setServiceStatus(java.lang.String serviceStatus) {
		this.serviceStatus = serviceStatus;
	}

	public java.util.List<com.myteam.tts_connected_claims.serviceTimelines> getServiceTimeline() {
		return this.serviceTimeline;
	}

	public void setServiceTimeline(
			java.util.List<com.myteam.tts_connected_claims.serviceTimelines> serviceTimeline) {
		this.serviceTimeline = serviceTimeline;
	}

	public java.lang.String getServiceTriggerSource() {
		return this.serviceTriggerSource;
	}

	public void setServiceTriggerSource(java.lang.String serviceTriggerSource) {
		this.serviceTriggerSource = serviceTriggerSource;
	}

	public java.lang.String getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(java.lang.String serviceType) {
		this.serviceType = serviceType;
	}

	public java.lang.String getVendorCaseCreatedTime() {
		return this.vendorCaseCreatedTime;
	}

	public void setVendorCaseCreatedTime(java.lang.String vendorCaseCreatedTime) {
		this.vendorCaseCreatedTime = vendorCaseCreatedTime;
	}

	public java.lang.String getVendorCaseId() {
		return this.vendorCaseId;
	}

	public void setVendorCaseId(java.lang.String vendorCaseId) {
		this.vendorCaseId = vendorCaseId;
	}

	public java.lang.String getVendorName() {
		return this.vendorName;
	}

	public void setVendorName(java.lang.String vendorName) {
		this.vendorName = vendorName;
	}

	public java.lang.String getVendorServiceCreatedTime() {
		return this.vendorServiceCreatedTime;
	}

	public void setVendorServiceCreatedTime(
			java.lang.String vendorServiceCreatedTime) {
		this.vendorServiceCreatedTime = vendorServiceCreatedTime;
	}

	public java.lang.String getVendorServiceId() {
		return this.vendorServiceId;
	}

	public void setVendorServiceId(java.lang.String vendorServiceId) {
		this.vendorServiceId = vendorServiceId;
	}

	public serviceDetails(
			com.myteam.tts_connected_claims.location actualDestination,
			java.lang.String containerId,
			com.myteam.tts_connected_claims.location customerDirectedDestination,
			com.myteam.tts_connected_claims.location directedDestination,
			java.lang.String incidentCaseType,
			java.lang.String incidentId,
			com.myteam.tts_connected_claims.location incidentLocation,
			java.lang.String incidentServiceType,
			java.lang.String instructionsToServiceProvider,
			java.lang.String parentId,
			java.lang.String processId,
			java.lang.String requestor,
			java.lang.String serviceId,
			java.lang.String serviceName,
			java.lang.String serviceProcessId,
			com.myteam.tts_connected_claims.serviceProvider serviceProvider,
			com.myteam.tts_connected_claims.serviceProviderCustomerLiasion serviceProviderCustomerLiaison,
			com.myteam.tts_connected_claims.serviceProviderLiaison serviceProviderLiaison,
			java.lang.String serviceProviderOnscene,
			java.lang.String serviceStatus,
			java.util.List<com.myteam.tts_connected_claims.serviceTimelines> serviceTimeline,
			java.lang.String serviceTriggerSource,
			java.lang.String serviceType,
			java.lang.String vendorCaseCreatedTime,
			java.lang.String vendorCaseId, java.lang.String vendorName,
			java.lang.String vendorServiceCreatedTime,
			java.lang.String vendorServiceId) {
		this.actualDestination = actualDestination;
		this.containerId = containerId;
		this.customerDirectedDestination = customerDirectedDestination;
		this.directedDestination = directedDestination;
		this.incidentCaseType = incidentCaseType;
		this.incidentId = incidentId;
		this.incidentLocation = incidentLocation;
		this.incidentServiceType = incidentServiceType;
		this.instructionsToServiceProvider = instructionsToServiceProvider;
		this.parentId = parentId;
		this.processId = processId;
		this.requestor = requestor;
		this.serviceId = serviceId;
		this.serviceName = serviceName;
		this.serviceProcessId = serviceProcessId;
		this.serviceProvider = serviceProvider;
		this.serviceProviderCustomerLiaison = serviceProviderCustomerLiaison;
		this.serviceProviderLiaison = serviceProviderLiaison;
		this.serviceProviderOnscene = serviceProviderOnscene;
		this.serviceStatus = serviceStatus;
		this.serviceTimeline = serviceTimeline;
		this.serviceTriggerSource = serviceTriggerSource;
		this.serviceType = serviceType;
		this.vendorCaseCreatedTime = vendorCaseCreatedTime;
		this.vendorCaseId = vendorCaseId;
		this.vendorName = vendorName;
		this.vendorServiceCreatedTime = vendorServiceCreatedTime;
		this.vendorServiceId = vendorServiceId;
	}

}