package com.myteam.tts_connected_claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class thirdPartyDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("saId")
	private java.lang.String saId;
	@org.kie.api.definition.type.Label("contactNumber")
	private java.lang.String contactNumber;
	@org.kie.api.definition.type.Label("driverName")
	private java.lang.String driverName;
	@org.kie.api.definition.type.Label("driverSurname")
	private java.lang.String driverSurname;
	@org.kie.api.definition.type.Label("email")
	private java.lang.String email;
	@org.kie.api.definition.type.Label("vehicleRegNumber")
	private java.lang.String vehicleRegNumber;
	@org.kie.api.definition.type.Label("makeModel")
	private java.lang.String makeModel;
	@org.kie.api.definition.type.Label("insuranceProvider")
	private java.lang.String insuranceProvider;

	@org.kie.api.definition.type.Label(value = "color")
	private java.lang.String color;

	public thirdPartyDetails() {
	}

	public java.lang.String getSaId() {
		return this.saId;
	}

	public void setSaId(java.lang.String saId) {
		this.saId = saId;
	}

	public java.lang.String getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(java.lang.String contactNumber) {
		this.contactNumber = contactNumber;
	}

	public java.lang.String getDriverName() {
		return this.driverName;
	}

	public void setDriverName(java.lang.String driverName) {
		this.driverName = driverName;
	}

	public java.lang.String getDriverSurname() {
		return this.driverSurname;
	}

	public void setDriverSurname(java.lang.String driverSurname) {
		this.driverSurname = driverSurname;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getVehicleRegNumber() {
		return this.vehicleRegNumber;
	}

	public void setVehicleRegNumber(java.lang.String vehicleRegNumber) {
		this.vehicleRegNumber = vehicleRegNumber;
	}

	public java.lang.String getMakeModel() {
		return this.makeModel;
	}

	public void setMakeModel(java.lang.String makeModel) {
		this.makeModel = makeModel;
	}

	public java.lang.String getInsuranceProvider() {
		return this.insuranceProvider;
	}

	public void setInsuranceProvider(java.lang.String insuranceProvider) {
		this.insuranceProvider = insuranceProvider;
	}

	public java.lang.String getColor() {
		return this.color;
	}

	public void setColor(java.lang.String color) {
		this.color = color;
	}

	public thirdPartyDetails(java.lang.String saId,
			java.lang.String contactNumber, java.lang.String driverName,
			java.lang.String driverSurname, java.lang.String email,
			java.lang.String vehicleRegNumber, java.lang.String makeModel,
			java.lang.String insuranceProvider, java.lang.String color) {
		this.saId = saId;
		this.contactNumber = contactNumber;
		this.driverName = driverName;
		this.driverSurname = driverSurname;
		this.email = email;
		this.vehicleRegNumber = vehicleRegNumber;
		this.makeModel = makeModel;
		this.insuranceProvider = insuranceProvider;
		this.color = color;
	}

}