package com.myteam.tts_connected_claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class vehicleOuterDamage implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "frontLeft")
	private java.lang.Boolean frontLeft;
	@org.kie.api.definition.type.Label(value = "frontCenter")
	private java.lang.Boolean frontCenter;
	@org.kie.api.definition.type.Label(value = "frontRight")
	private java.lang.Boolean frontRight;
	@org.kie.api.definition.type.Label(value = "centerLeft")
	private java.lang.Boolean centerLeft;
	@org.kie.api.definition.type.Label(value = "centerRight")
	private java.lang.Boolean centerRight;
	@org.kie.api.definition.type.Label(value = "rearLeft")
	private java.lang.Boolean rearLeft;
	@org.kie.api.definition.type.Label(value = "rearCenter")
	private java.lang.Boolean rearCenter;
	@org.kie.api.definition.type.Label(value = "rearRight")
	private java.lang.Boolean rearRight;

	public vehicleOuterDamage() {
	}

	public java.lang.Boolean getFrontLeft() {
		return this.frontLeft;
	}

	public void setFrontLeft(java.lang.Boolean frontLeft) {
		this.frontLeft = frontLeft;
	}

	public java.lang.Boolean getFrontCenter() {
		return this.frontCenter;
	}

	public void setFrontCenter(java.lang.Boolean frontCenter) {
		this.frontCenter = frontCenter;
	}

	public java.lang.Boolean getFrontRight() {
		return this.frontRight;
	}

	public void setFrontRight(java.lang.Boolean frontRight) {
		this.frontRight = frontRight;
	}

	public java.lang.Boolean getCenterLeft() {
		return this.centerLeft;
	}

	public void setCenterLeft(java.lang.Boolean centerLeft) {
		this.centerLeft = centerLeft;
	}

	public java.lang.Boolean getCenterRight() {
		return this.centerRight;
	}

	public void setCenterRight(java.lang.Boolean centerRight) {
		this.centerRight = centerRight;
	}

	public java.lang.Boolean getRearLeft() {
		return this.rearLeft;
	}

	public void setRearLeft(java.lang.Boolean rearLeft) {
		this.rearLeft = rearLeft;
	}

	public java.lang.Boolean getRearCenter() {
		return this.rearCenter;
	}

	public void setRearCenter(java.lang.Boolean rearCenter) {
		this.rearCenter = rearCenter;
	}

	public java.lang.Boolean getRearRight() {
		return this.rearRight;
	}

	public void setRearRight(java.lang.Boolean rearRight) {
		this.rearRight = rearRight;
	}

	public vehicleOuterDamage(java.lang.Boolean frontLeft,
			java.lang.Boolean frontCenter, java.lang.Boolean frontRight,
			java.lang.Boolean centerLeft, java.lang.Boolean centerRight,
			java.lang.Boolean rearLeft, java.lang.Boolean rearCenter,
			java.lang.Boolean rearRight) {
		this.frontLeft = frontLeft;
		this.frontCenter = frontCenter;
		this.frontRight = frontRight;
		this.centerLeft = centerLeft;
		this.centerRight = centerRight;
		this.rearLeft = rearLeft;
		this.rearCenter = rearCenter;
		this.rearRight = rearRight;
	}

}